apiVersion: v1
kind: Secret
metadata:
  name: django-secret
type: Opaque
data:
  SECRET_KEY: ZGphbmdvLWluc2VjdXJlLWt2NTNfIzhtLWo3IV93cWMtNmohLWhANnBtODghb2okKzZtJm8NCg==
  POSTGRES_USER: bWl0cmFqZWV0DQo=
  POSTGRES_PASSWORD: aG90ZWxNYW5hZ2VtZW50QDEyMzQNCg==
