version: "3.9"
services:
  # Django application image building
  web:
    depends_on:
      - db
    build:
      context: ./hotel_management_system
      dockerfile: Dockerfile
    image: hotel-management-k8s
    environment:
      - PORT=8000
    env_file:
      - ./hotel_management_system/.env
    ports:
      - "8000:8000"
    
  # PostgreSQL Database image building
  db:
    image: postgres
    restart: always 
    command: -p 5433
    env_file:
      - ./hotel_management_system/.env
    expose:
      - 5433
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data:
