# Generated by Django 4.0.4 on 2022-06-01 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('room_id', models.UUIDField(primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('room_type', models.CharField(max_length=100)),
                ('rate', models.IntegerField()),
                ('smoking', models.BooleanField(default=False)),
                ('floor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('additional_fees', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='main.rooms')),
            ],
        ),
    ]
