# Generated by Django 4.0.4 on 2022-06-01 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rooms_room_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='reserved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rooms',
            name='room_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Standard No AC', 'Standard No AC'), ('Deluxe', 'Deluxe'), ('Suite', 'Suite')], max_length=100),
        ),
    ]
