apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
# This data is base64 encoded
  database: aG90ZWxfbWFuYWdlbWVudF9zeXN0ZW0NCg==
  username: bWl0cmFqZWV0DQo=
  password: aG90ZWxNYW5hZ2VtZW50QDEyMzQNCg==
