# Generated by Django 4.0.4 on 2022-06-01 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_id', models.UUIDField()),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Rather not Say')], max_length=100)),
                ('highest_qualification', models.CharField(choices=[(0, '12th pass'), (1, 'B.Tech.'), (2, 'BBA'), (3, 'MBA')], max_length=100)),
                ('staff_type', models.CharField(choices=[('M', 'Management'), ('Service', (('SH', 'House Keeping'), ('SK', 'Laundry'), ('SL', 'Kitchen')))], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_proof', models.ImageField(upload_to='id_proof/%Y/%m/%d/')),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'Rather not Say')], max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
