# Generated by Django 4.0.4 on 2022-06-01 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id',
        ),
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='staff_type',
            field=models.CharField(choices=[('M', 'Management'), ('Service', (('SH', 'House Keeping'), ('SL', 'Laundry'), ('SK', 'Kitchen')))], max_length=100),
        ),
    ]
